// One source for the model-visible definition and on-demand REPL help.
export const REPL_GUIDE = `Persistent, branch-shared JavaScript workspace where the parent and its subagents capture tool results and process them before revealing selected output. Prefer REPL for web research, sifting through logs/long command output, large search/API results, structured-data comparisons, and extracting relevant evidence from large context sources. Reuse stored data and coordinate distinct output variables across agents. Use direct tools for simple actions, routine code editing, or special UI/context output; REPL usage is optional.

WORKFLOW
1. Capture: {"action":"invoke","tool":"read_file","args":{"path":"package.json"},"assign":"file"}. Required: tool, assign; args defaults to {}. The complete returned JSON value is stored as file, not printed. The receipt reports status:"stored", variable and toolStatus. The result is exactly the tool's returned object/string, not automatically unwrapped, parsed or expanded beyond the tool's own truncation.
2. Learn shape: {"action":"inspect","variable":"file"} returns type, string/array length or up to 30 object keys. Do not assume every tool uses the same content field. To inspect a nested field, first create an alias with exec, e.g. var data = page.data; then inspect data. Use a small show budget when you need sample values.
3. Process: {"action":"exec","code":"var manifest = JSON.parse(file.content); var dependencies = Object.keys(manifest.dependencies || {});"}. Use top-level var for persistent, inspectable variables. let/const lexical bindings are not listed or accessible through inspect/show. Reuse stored results rather than fetching again. exec completion values never print. Optionally combine processing and disclosure: {"action":"exec","code":"var dependencies = Object.keys(manifest.dependencies || {});","show":"dependencies","maxOutputChars":2000}. show is a variable name, not an expression or boolean; omit it to keep exec silent. Execution and show share one queued cell, with the same output limits/pagination as action:show. If execution fails, no output is shown; if show fails after execution, state changes remain—use inspect/show without rerunning exec.
4. Reveal only selected evidence: {"action":"show","variable":"dependencies","maxOutputChars":2000}. Strings display directly; other values use JSON. show defaults to 4000 content characters, maximum 20000; returns totalChars, truncated and nextOffset. Continue with {"action":"show","variable":"dependencies","offset":2000,"maxOutputChars":2000}, using the returned nextOffset. Prefer filtering/slicing locally over paging an entire large result.
5. Manage: {"action":"list"} lists up to 100 variables with shape information; {"action":"drop","variable":"file"} removes a binding; {\"action\":\"reset\"} discards the shared workspace (parent-only). invoke requires overwrite:true to replace an existing writable variable. Use an identifier of 1–64 characters for assign/variable, not an expression such as page.data.

JSON ARTIFACTS (MANUAL SAVE/RESTORE)
Export one selected variable without copying its contents into model context: {"action":"export","variable":"benchmarkResults","path":"benchmarks/results/run-001.json"}. Requires Agent mode and create_file availability/permission. Import after restart: {"action":"import","path":"benchmarks/results/run-001.json","assign":"benchmarkResults"}. Requires read_file; allowed in Chat mode. Both return metadata only. Existing file (export) or writable variable (import) requires overwrite:true; default false. Files use normal workspace/managed-path restrictions and hooks. Parent directories are created for export. Export receipts identify the snapshot revision, which may differ from the current workspace after concurrent operations.
Artifacts are plain JSON, at most 5 MiB UTF-8, with depth 64/node 100000 and CPU/memory bounds. Supports null, booleans, strings, finite numbers, dense arrays and plain data objects; rejects cycles, functions, undefined, symbols, BigInt, accessors, extra array properties and unsupported prototypes. No getters/toJSON are called by the serializer; proxy reflection can still run traps under the sandbox deadline. Shared-reference identity and negative zero are not preserved. Import parses data, never executes code, and rejects invalid/truncated/oversized input without replacing the destination. Concurrent import overwrite conflicts retain parsed data under resultVariable, as with invoke. Capture reservations and cancellation rules apply to import too.
This is not automatic persistence: only explicitly exported data survives restart, not later changes, functions or running tasks. reset/drop never delete exported files. Select artifacts deliberately: files are plaintext and may contain sensitive data. Normal tool-job storage and authorized hook context still apply. A cancelled/failed export may have written a file; inspect before retrying. Use multiple smaller artifacts for larger datasets.

BROWSING EXAMPLE
After invoke browse_web into page, inspect page first. If its shape contains data.content, run {"action":"exec","code":"var passages = page.data.content.split(/\\n\\n+/).filter(p => /license|pricing/i.test(p)); var selected = passages.slice(0, 5);","show":"selected","maxOutputChars":2000}. Preserve source URL/provenance when constructing findings. If filtering produces no matches, inspect samples and surrounding content before treating that as evidence of absence.

EXECUTION AND SAFETY
exec is synchronous JavaScript in isolated QuickJS: no Node/process/require, filesystem, network, imports, console, tools.call, await-based tool invocation, or show() function inside code. Call tools via action:invoke. Display via action:show or the optional show parameter on action:exec; there is no show() function inside code. Code is capped at 32000 characters; timeoutMs defaults to 100 ms, range 1–250 ms. Normal tool deadlines apply to invoke, not this CPU timeout. State operations queue in FIFO order (up to 64 pending cells). Invoke reserves its destination, releases the workspace while the tool runs, then queues storage; up to 16 captures can run concurrently. Use different destination names for parallel captures. Tools/subagent waits never hold the workspace lock.
Only tools available to this caller can be invoked. Each invocation retains normal permissions, hooks, operation-mode checks and cancellation. REPL is not a privilege bypass. invoke stores errors too: toolStatus:"error" means inspect/show the assigned error before proceeding. Cancellation propagates. Concurrent mutation during overwrite returns status:conflict without replacing the destination, and retains the tool result in resultVariable; inspect/show that variable instead of repeating the tool. Conflict detection is conservative for any intervening exec/drop, including failed cells with partial changes. A tool may complete its side effect even if later storage fails; never blindly retry mutations. Failed exec can leave partial variable changes; there is no transaction rollback or automatic replay.
Use these directly, not through invoke: repl, multi_call, skill_manager, html_renderer, view_image, and plan_md action:display. Other split-channel results may store metadata only (metadataOnly:true); use the original tool directly to see its special output. Subagent calls are allowed only where already available; REPL does not enable nested subagents.

STATE AND LIMITS
Parent and subagents on the same branch and filesystem root share ALL REPL variables and can read/mutate them. Other branches, conversations and roots remain isolated. Direct HTTP subagents have private run-scoped workspaces. Use distinct names or a shared object for coordinated findings. Receipts include workspace revision and lastWriter (agent run ID or main). Reset of a shared branch is parent-only (standalone private children can reset their own scope) and rejected while captures are in flight; drop rejects reserved destinations. Sessions are memory-only: server restart loses them; after 30 minutes idle they expire when a later REPL request reclaims them. Use list to check state after a long gap. Up to 16 sessions per dispatcher, 32 MiB guest heap per session, and 8 MiB plain JSON per captured result, with additional serialization/work limits. Full results stay out of automatic model history, but existing tool-job storage and hooks retain their normal behavior. Only explicit inspect/show (including exec with show) disclose selected data.

HELP
Call {"howto":true} anytime to retrieve this same guide. action is optional for help. howto:true is help-only even if other fields are supplied: it does not invoke a tool, execute code, create/reset a session or reveal stored values.`
